export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const SET_REFRESHING = 'SET_REFRESHING';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
